# Generated by Django 5.0.4 on 2024-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinventory',
            name='cars_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
